name: Build Libs

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Platform/**'
      - '!Platform/libs/**'
  pull_request:
    paths:
      - 'Platform/**'
      - '!Platform/libs/**'
jobs:
  Build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            lib: x64/FosterPlatform.dll
          #- os: macos-latest
          #  lib: osx/libFosterPlatform.dylib
          - os: ubuntu-latest
            lib: lib64/libFosterPlatform.so
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Get CMake
        uses: lukka/get-cmake@v3.27.4
      - name: CMake Configure
        run: cmake -B build -S Platform
      - name: CMake Build
        run: cmake --build build --config Release
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{matrix.os}}-build
          path: Platform/libs/${{matrix.lib}}
  UpdateLibs:
    needs: [Build]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Download windows lib
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-build
          path: Platform/libs/x64
      - name: Download ubuntu lib
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-build
          path: Platform/libs/lib64
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Platform/libs
